### ISSUE TITLE
p-2

### ISSUE THREAD

**Issue by crmsoft** [crmsoft/gpost#4]
*p-2* clasini variables.scss icinde $postBlockPaddings gibi bir degisken tanimlayarak, kendimize gore  bir class tanimlayabilir miyiz ?

**Comment by etunadev** [comment]
postBlockPaddings  adında  bir class tanımladım  bir  method  ile değişkenler  yardımı  ile içeriğini  düzenledim variables.sass  dosyasından  inceleyebilirsiniz
